In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv("GRDP_시_군_구__20231226155747.csv", na_values="?")
df

     행정구역별(1)  행정구역별(2)         2019       2019.1
0    행정구역별(1)  행정구역별(2)        당해년가격  2015년 기준년가격
1       서울특별시        소계  435,927,212  414,092,568
2         NaN       종로구   33,780,610   32,427,863
3         NaN        중구   53,823,217   52,869,673
4         NaN       용산구   12,695,516   11,992,461
..        ...       ...          ...          ...
240       NaN       거창군    1,599,712    1,521,518
241       NaN       합천군    1,125,887    1,077,016
242   제주특별자치도        소계   20,308,737   19,186,190
243       NaN       제주시   14,859,505   14,134,135
244       NaN      서귀포시    5,449,232    5,064,244

[245 rows x 4 columns]

In [2]:
# 결측치 확인
def check_missing_col(dataframe):
    missing_col = []
    for col in dataframe.columns:
        missing_values = sum(dataframe[col].isna())
        is_missing = True if missing_values >= 1 else False
        if is_missing:
            print(f'결측치가 있는 컬럼은: {col} 입니다')
            print(f'해당 컬럼에 총 {missing_values} 개의 결측치가 존재합니다.')
            missing_col.append([col, dataframe[col].dtype])
    if missing_col == []:
        print('결측치가 존재하지 않습니다')
    return missing_col

missing_col = check_missing_col(df)
#행정구역별(1)의 결측치는 무시 가능함

결측치가 있는 컬럼은: 행정구역별(1) 입니다
해당 컬럼에 총 228 개의 결측치가 존재합니다.

In [3]:
#필요없는 열 삭제

del df['2019.1']
df

     행정구역별(1)  행정구역별(2)         2019
0    행정구역별(1)  행정구역별(2)        당해년가격
1       서울특별시        소계  435,927,212
2         NaN       종로구   33,780,610
3         NaN        중구   53,823,217
4         NaN       용산구   12,695,516
..        ...       ...          ...
240       NaN       거창군    1,599,712
241       NaN       합천군    1,125,887
242   제주특별자치도        소계   20,308,737
243       NaN       제주시   14,859,505
244       NaN      서귀포시    5,449,232

[245 rows x 3 columns]

In [4]:
df.to_csv("C:/final/결측치제거GRDP_시_군_구__20231226155747.csv", index=False)