In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv("인구_십만명당_문화기반시설수_시도_시_군_구__20231226152752.csv", na_values="?")
df

       행정구역별                             2021          2021.1         2021.2
0      행정구역별  인구십만명당 문화기반시설수(A÷B×100,000) (개)  문화기반시설수(A) (개)  주민등록인구(B) (명)
1         전국                              6.1           3,145     51,638,809
2      서울특별시                              4.6             435      9,509,458
3     　　　종로구                             47.0              68        144,683
4      　　　중구                             24.5              30        122,499
..       ...                              ...             ...            ...
242   　　　거창군                              9.8               6         61,073
243   　　　합천군                             14.0               6         42,935
244  제주특별자치도                             19.2             130        676,759
245   　　　제주시                             14.0              69        493,096
246  　　　서귀포시                             33.2              61        183,663

[247 rows x 4 columns]

In [2]:
# 결측치 확인
def check_missing_col(dataframe):
    missing_col = []
    for col in dataframe.columns:
        missing_values = sum(dataframe[col].isna())
        is_missing = True if missing_values >= 1 else False
        if is_missing:
            print(f'결측치가 있는 컬럼은: {col} 입니다')
            print(f'해당 컬럼에 총 {missing_values} 개의 결측치가 존재합니다.')
            missing_col.append([col, dataframe[col].dtype])
    if missing_col == []:
        print('결측치가 존재하지 않습니다')
    return missing_col

missing_col = check_missing_col(df)

결측치가 존재하지 않습니다

In [3]:
#필요없는 열 삭제

del df['2021.1']
del df['2021.2']
df

       행정구역별                             2021
0      행정구역별  인구십만명당 문화기반시설수(A÷B×100,000) (개)
1         전국                              6.1
2      서울특별시                              4.6
3     　　　종로구                             47.0
4      　　　중구                             24.5
..       ...                              ...
242   　　　거창군                              9.8
243   　　　합천군                             14.0
244  제주특별자치도                             19.2
245   　　　제주시                             14.0
246  　　　서귀포시                             33.2

[247 rows x 2 columns]

In [4]:
df.to_csv("C:/final/결측치제거인구_십만명당_문화기반시설수_시도_시_군_구.csv", index=False)